---
# Внешний порт, на котором публикуется контейнер Redmine
redmine_port: 3000

# Версия образа Redmine
redmine_version: "6.0.10"

# Установка pip и его модулей (роль geerlingguy.pip)
pip_package: python3-pip
pip_install_packages:
  - name: docker
  - name: requests
